name: reddit-place-script-2022
base: core20
adopt-info: main
summary: Script to draw an image onto r/place
description: |
  This is a script to draw a JPG onto r/place (https://www.reddit.com/r/place/).

grade: devel
confinement: strict

parts:
  main:
    source: https://github.com/rdeepak2002/reddit-place-script-2022.git
    plugin: python
    
